spring.datasource.url=jdbc:postgresql://dpg-d746dudactks7389t5kg-a/portfolio_db_bnyj
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.main.lazy-initialization=true
spring.h2.console.enabled=false

# Mail la App Password viene de variable de entorno MAIL_PASSWORD
spring.mail.password=${MAIL_PASSWORD}
