spring.datasource.url=jdbc:postgresql://dpg-d746dudactks7389t5kg-a/portfolio_db_bnyj
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false

# Resend email API
resend.api-key=${RESEND_API_KEY}
